spring.application.name=demo
# ===============================
# Optional: Server Port
# ===============================
server.port=8181

# ===============================
# PostgreSQL Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/eand
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Connection Pool (HikariCP)
# ===============================
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000


eand.batch.job.base.url=http://localhost:8181/api/batch-job
eand.batch.job.reinitiate.url=/consumer
eand.batch.job.queue.name=batch-job-queue